# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: byan <byan@student.42seoul.kr>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/24 20:26:19 by byan              #+#    #+#              #
#    Updated: 2021/10/24 21:01:20 by byan             ###   ########seoul.kr   #
#                                                                              #
# **************************************************************************** #

SRC		= main.c ft_final.c ft_bsq.c ft_error.c ft_make.c ft_read.c
SRCS	= ${addprefix ${PRE}, ${SRC}}
OBJS	= ${SRCS:.c=.o}
PRE		= ./srcs/
HEAD	= ./includes/
NAME	= bsq
RM		= rm -f
GCC		= gcc
CFLAGS	= -Wall -Werror -Wextra
all:	${NAME}

dep:
			gccmakedep $(INC) $(SRCS)

.c.o:
			${GCC} ${CFLAGS} -c -I ${HEAD} $< -o ${<:.c=.o}

${NAME}:	${OBJS}
			${GCC} ${CFLAGS} -o ${NAME} ${OBJS}

clean:
			rm -f ${OBJS}

fclean:		clean
			rm -f ${NAME}

re:			fclean all

.PHONY:		all clean fclean re